### ISSUE TITLE
TBD and remaining issues

### ISSUE THREAD

**Issue by RoseannaM** [netlify/gocommerce#159]
- [ ] #136 https://github.com/netlify/gocommerce-js/issues/20 https://github.com/netlify/gocommerce-admin/issues/18 Implement the bulk delete changes in the[ client library](https://github.com/netlify/gocommerce-js)
- [x] ~~#138 Decide on search provider/implement search.~~ Lets keep our search as is for now
- [ ] #143 Decide on name determination logic. Currently we display 'name' as this is what the identity widgent uses. Designs call for firstname, lastname. https://github.com/netlify/gocommerce-admin/issues/19
- [ ] #152  https://github.com/netlify/gocommerce-js/issues/21 Negation API call for orders in the[ client library](https://github.com/netlify/gocommerce-js)
- [ ] #158 Identify bug with orders api.

**Comment by bcomnes** [comment]
#158 should be fixed, should we make a gc-admin issue to accommodate the fix?

**Comment by bcomnes** [comment]
Closing this in favor of the project board: https://github.com/orgs/netlify/projects/28?fullscreen=true

Lets get every open issue on your plate on there, and have you assigned to them.  I think I already got that mostly done.
